Add support to verify and get alert text
MarketSquare/robotframework-browser pull request #1010
Opened 2021-05-18 17:22 UTC by aaltat

Fixes #440

2021-05-18 17:41 UTC, mkorpela commented on node/playwright-wrapper/interaction.ts
> +    if (alertAction == 'accept' && promptInput) {
Please use `===`

2021-05-18 17:41 UTC, mkorpela commented on node/playwright-wrapper/interaction.ts
> +    } else if (alertAction == 'accept') {
Please use `===`

2021-05-18 17:42 UTC, mkorpela requested changes
Equals in js is the shit. Use === instead of ==

2021-05-18 20:13 UTC, emakaay commented
@aaltat  👍  looking good !

2021-05-19 16:14 UTC, merged

2021-05-19 16:18 UTC, aaltat commented
@emakaay  this is not merged to master. If you want, you can install directly from GitHub repo with pip and give it a try.

2021-05-21 05:57 UTC, emakaay commented
Thanks Tatu,
I'm already using this feature, and it works brilliantly.

Greets,
Erik

On Wed, May 19, 2021, 18:18 Tatu Aalto ***@***.***> wrote:

> @emakaay <https://github.com/emakaay> this is now merged to master. If
> you want, you can install directly from GitHub repo with pip and give it a
> try.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/MarketSquare/robotframework-browser/pull/1010#issuecomment-844259127>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARLATWLOLWYE3ISC5SLRRN3TOPQF7ANCNFSM45C6KNYQ>
> .
>