New `Evaluate Multiline JavaScript` Keyword
MarketSquare/robotframework-browser pull request #1854
Opened 2022-03-12 00:25 UTC by Snooz82

```robotframework
Evaluate Multiline JavaScript
    ${texts}=    Evaluate Multiline JavaScript    button
    ...    (elements, arg) => {
    ...      let text = []
    ...      for (e of elements) {
    ...        console.log(e.innerText)
    ...        text.push(e.innerText)
    ...      }
    ...      text.push(arg)
    ...      return text
    ...    }
    ...    all_elements=True
    ...    arg=${{[1,2,3]}}
    Length Should Be    ${texts}    12
    Should Be Equal    ${texts}[-1]    ${{[1,2,3]}}
 ```

2022-03-12 15:44 UTC, Snooz82 commented
I am done here. Works well imho.

2022-03-13 12:40 UTC, mkorpela requested changes

2022-03-13 12:45 UTC, mkorpela commented on node/playwright-wrapper/evaluation.ts
> +    let result;
extract method.

2022-03-13 14:23 UTC, mkorpela approved these changes

2022-03-13 15:16 UTC, merged