Added Playwright 1.20 features to `Take Screenshot`
MarketSquare/robotframework-browser pull request #1921
Opened 2022-04-01 19:17 UTC by Snooz82

- [ ] adding masking
- [ ] adding omit_background
- [ ] adding disable_animations

2022-04-02 20:19 UTC, mkorpela requested changes

2022-04-02 20:19 UTC, mkorpela commented on node/playwright-wrapper/browser-control.ts
> +        //const maskLoc = await findLocator(state, options['mask'], strictMode, undefined, true);
maybe remove this?

2022-04-03 14:48 UTC, Snooz82 commented on node/playwright-wrapper/browser-control.ts
> +        //const maskLoc = await findLocator(state, options['mask'], strictMode, undefined, true);
Done

2022-04-03 14:48 UTC, Snooz82 commented on atest/library/screenshot.py
> +    return im.size
resolved

2022-04-03 15:05 UTC, merged